### ISSUE TITLE
converted video not found

### ISSUE THREAD

**Issue by mflorange** [senshu/Sozi-export#11]
Hi,
I have an issue when I try to convert my sozi presentation in video.
When I write the command in my terminal, it opens the video and plays it (which is perfect) but after that I can find the result in my files. What did I do wrong?

**Comment by aumouvantsillage** [comment]
> What did I do wrong?

If you gave me the exact command that you typed, maybe I could answer.

**Comment by mflorange** [comment]
sure! sorry...here is what I typed :sozi-to-video /Users/Doudou/Downloads/first-presentation.sozi.html

      De : Guillaume Savaton <notifications@github.com>
 À : senshu/Sozi-export <Sozi-export@noreply.github.com> 
Cc : mflorange <marjorieballot@yahoo.fr>; Author <author@noreply.github.com>
 Envoyé le : Dimanche 26 mars 2017 22h57
 Objet : Re: [senshu/Sozi-export] converted video not found (#11)
   

What did I do wrong?
If you gave me the exact command that you typed, maybe I could answer.—

**Comment by aumouvantsillage** [comment]
I see that you did not set the `-o` (or `--output`) command-line option, but it is optional.
Your video should be saved to `/Users/Doudou/Downloads/first-presentation.sozi.ogv`.

`sozi-to-video` uses `libav` to generate the video file. Can you check that it is correctly installed.
In a terminal, run:

```
avconv
```

And tell me what you see.

**Comment by mflorange** [comment]
Here is the terminal answer : -sh: avconv: command not foundI suppose that this is not the expected answer...Do I have to install libav (and how)?

      De : Guillaume Savaton <notifications@github.com>
 À : senshu/Sozi-export <Sozi-export@noreply.github.com> 
Cc : mflorange <marjorieballot@yahoo.fr>; Author <author@noreply.github.com>
 Envoyé le : Lundi 27 mars 2017 13h58
 Objet : Re: [senshu/Sozi-export] converted video not found (#11)
   
I see that you did not set the -o (or --output) command-line option, but it is optional.
Your video should be saved to /Users/Doudou/Downloads/first-presentation.sozi.ogv.sozi-to-video uses libav to generate the video file. Can you check that it is correctly installed.
In a terminal, run:avconv
And tell me what you see.—

**Comment by aumouvantsillage** [comment]
> Do I have to install libav (and how)?

Yes.
I assume that you are using OS X. I have never tried, but you may find answers here: https://superuser.com/questions/568464/how-to-install-libav-avconv-on-osx

**Comment by mflorange** [comment]
OK so I installed libav.When I type avconv in the terminal, I get : avconv version 12, Copyright (c) 2000-2016 the Libav developers  built on Mar  6 2017 22:35:59 with Apple LLVM version 8.0.0 (clang-800.0.42.1)Hyper fast Audio and Video encoderusage: avconv [options] [[infile options] -i infile]... {[outfile options] outfile}...
Use -h to get full help or, even better, run 'man avconv'
I tried again to export my sozi presentation and the problem remains : it plays the video but no .ogv file is created.Any other idea?

      De : Guillaume Savaton <notifications@github.com>
 À : senshu/Sozi-export <Sozi-export@noreply.github.com> 
Cc : mflorange <marjorieballot@yahoo.fr>; Author <author@noreply.github.com>
 Envoyé le : Lundi 27 mars 2017 14h20
 Objet : Re: [senshu/Sozi-export] converted video not found (#11)
   

Do I have to install libav (and how)?
Yes.
I assume that you are using OS X. I have never tried, but you may find answers here: https://superuser.com/questions/568464/how-to-install-libav-avconv-on-osx—

**Comment by aumouvantsillage** [comment]
> Any other idea?

Are there any messages in the terminal when you run `sozi-to-video`?

**Comment by mflorange** [comment]
just : Converting /Users/Doudou/Downloads/first-presentation.sozi.html to /Users/Doudou/Downloads/first-presentation.sozi.ogvsozi-to-video.js> Exporting frame: 1sozi-to-video.js> Exporting frame: 2sozi-to-video.js> Exporting frame: 3


      De : Guillaume Savaton <notifications@github.com>
 À : senshu/Sozi-export <Sozi-export@noreply.github.com> 
Cc : mflorange <marjorieballot@yahoo.fr>; Author <author@noreply.github.com>
 Envoyé le : Lundi 27 mars 2017 21h48
 Objet : Re: [senshu/Sozi-export] converted video not found (#11)
   

Any other idea?
Are there any messages in the terminal when you run sozi-to-video?—

**Comment by aumouvantsillage** [comment]
Did you create the presentation yourself or are you trying to convert the HTML file that can be downloaded at the end of the tutorial at http://sozi.baierouge.fr/pages/tutorial-first.html ?
In the first case, which version of Sozi are you using?

I don't have a Mac, so I have never tried to make `sozi-export` work on that platform.
Without any error message or other indication, I have no mean to diagnose the problem.

You can contact the Sozi users group at https://groups.google.com/forum/#!forum/sozi-users
Maybe another Mac user can help you.

**Comment by mflorange** [comment]
I used the svg document from the first presentation on the sozi website to make a new presentation.I just created a new presentation and tried to export it as video, just to be sure but the problem remains.My version of sozi is the last one available (17.02).Do you if this could word on windows? I have access to a PC so I could try that.I will try tu sozi users group as well.
      De : Guillaume Savaton <notifications@github.com>
 À : senshu/Sozi-export <Sozi-export@noreply.github.com> 
Cc : mflorange <marjorieballot@yahoo.fr>; Author <author@noreply.github.com>
 Envoyé le : Mardi 28 mars 2017 11h37
 Objet : Re: [senshu/Sozi-export] converted video not found (#11)
   
Did you create the presentation yourself or are you trying to convert the HTML file that can be downloaded at the end of the tutorial at http://sozi.baierouge.fr/pages/tutorial-first.html ?
In the first case, which version of Sozi are you using?I don't have a Mac, so I have never tried to make sozi-export work on that platform.
Without any error message or other indication, I have no mean to diagnose the problem.You can contact the Sozi users group at https://groups.google.com/forum/#!forum/sozi-users
Maybe another Mac user can help you.—

**Comment by mflorange** [comment]
My mistake : I had an ancient version (16.02 apparently). I just tried to run the new version... and can't open any svg document with it!When I select a sag document and click open, nothing happens...


      De : Guillaume Savaton <notifications@github.com>
 À : senshu/Sozi-export <Sozi-export@noreply.github.com> 
Cc : mflorange <marjorieballot@yahoo.fr>; Author <author@noreply.github.com>
 Envoyé le : Mardi 28 mars 2017 11h37
 Objet : Re: [senshu/Sozi-export] converted video not found (#11)
   
Did you create the presentation yourself or are you trying to convert the HTML file that can be downloaded at the end of the tutorial at http://sozi.baierouge.fr/pages/tutorial-first.html ?
In the first case, which version of Sozi are you using?I don't have a Mac, so I have never tried to make sozi-export work on that platform.
Without any error message or other indication, I have no mean to diagnose the problem.You can contact the Sozi users group at https://groups.google.com/forum/#!forum/sozi-users
Maybe another Mac user can help you.—

**Comment by aumouvantsillage** [comment]
I cannot help you with Windows and OS X. I do all my tests on a Linux PC.
Version 17.02 was released in January for testers and nobody reported issues on these platforms.

**Comment by mflorange** [comment]
OK. Thanks for your help.

      De : Guillaume Savaton <notifications@github.com>
 À : senshu/Sozi-export <Sozi-export@noreply.github.com> 
Cc : mflorange <marjorieballot@yahoo.fr>; Author <author@noreply.github.com>
 Envoyé le : Mardi 28 mars 2017 18h14
 Objet : Re: [senshu/Sozi-export] converted video not found (#11)
   
I cannot help you with Windows and OS X. I do all my tests on a Linux PC.
Version 17.02 was released in January for testers and nobody reported issues on these platforms.—
