### ISSUE TITLE
Document local install

### ISSUE THREAD

**Issue by jeanparpaillon** [senshu/Sozi-export#2]
Hi,
Can you document the way to use Sozi-export from git ?

**Comment by aumouvantsillage** [comment]
I'm not sure I understand what you mean.
Sozi-export is currently documented in the [README](https://github.com/senshu/Sozi-export/blob/master/README.md) file of this project.

If you find these instructions incomplete or difficult to understand, can you please tell me which parts need to be modified?

**Comment by jeanparpaillon** [comment]
I'm not familiar with npm, it's not clear if my install fails because of misuse of npm or else.

# npm install -g sozi-export:

$ sudo npm install -g sozi-export
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
\

> slimerjs@0.9.6-2 install /usr/local/lib/node_modules/sozi-export/node_modules/slimerjs
> node install.js

SlimerJS not found on PATH
Downloading https://download.slimerjs.org/releases/0.9.6/slimerjs-0.9.6-linux-x86_64.tar.bz2
Saving to /usr/local/lib/node_modules/sozi-export/node_modules/slimerjs/slimerjs/slimerjs-0.9.6-linux-x86_64.tar.bz2
Receiving...
  [========================================] 100% 0.0s
Received 33587K total.
Extracting tar contents (via spawned process)
Removing /usr/local/lib/node_modules/sozi-export/node_modules/slimerjs/lib/slimer
Copying extracted folder /usr/local/lib/node_modules/sozi-export/node_modules/slimerjs/slimerjs/slimerjs-0.9.6-linux-x86_64.tar.bz2-extract-1453105354704/slimerjs-0.9.6 -> /usr/local/lib/node_modules/sozi-export/node_modules/slimerjs/lib/slimer
Writing location.js file
Done. SlimerJS binary available at /usr/local/lib/node_modules/sozi-export/node_modules/slimerjs/lib/slimer/slimerjs
npm ERR! Error: ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/sozi-export/cli/sozi-to-video.js'
npm ERR!     at Error (native)
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Linux 4.3.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "sozi-export"
npm ERR! cwd /home/jean/BA_Projets/git/Sozi-export
npm ERR! node -v v4.2.4
npm ERR! npm -v 1.4.21
npm ERR! path /usr/local/lib/node_modules/sozi-export/cli/sozi-to-video.js
npm ERR! syscall chmod
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/jean/BA_Projets/git/Sozi-export/npm-debug.log
npm ERR! not ok code 0

# And local install fails too:

$ npm install sozi-export
npm WARN install Refusing to install sozi-export as a dependency of itself

**Comment by aumouvantsillage** [comment]
I have published an update that should fix this issue. Please tell me if it works for you.

**Comment by jeanparpaillon** [comment]
Works for me, thanks :)
