### ISSUE TITLE
Fails with embedded mp4 video

### ISSUE THREAD

**Issue by cerisara** [senshu/Sozi-export#21]
I used the video plugin within Inkscape to add an mp4 video in my svg file, and then use sozi to output the html file: it works perfectly in the browser.
But when I try to convert to ogv with:

sozi-to-video tt.sozi.html

it does produce an ogv output file with the video until it reaches the frame where I have
embedded the mp4 video: the output ogv ends here, just before the embedded mp4 should start.

sozi version 19.04.22
ubuntu 18.04

**Comment by aumouvantsillage** [comment]
Yes. This is a known limitation of this tool: it cannot export presentations that contain embedded videos.
There is currently no plan to make it work in the near future.

I should add a warning about this in the documentation.

**Comment by cerisara** [comment]
Thank you for your answer. It's OK, I've found a workaround: I don't embed the video in sozi, but
add it later on with ffmpeg (overlay).
