### ISSUE TITLE
Do arguments -w and -h work?

### ISSUE THREAD

**Issue by thubalek** [senshu/Sozi-export#24]
I tried to create video using command `sozi-to-video -w 960 -h 540 -b 10M presentation.sozi.html` but created video was of dimensions `1024x768`.

Do you have any idea what is wrong?

**Comment by thubalek** [comment]
Ok, nevermind. Correct argument is `-W` not `-w`. I overlooked it. Sorry about confusion.

**Comment by aumouvantsillage** [comment]
Great. I'm closing this issue.
