### ISSUE TITLE
Installation breaks

### ISSUE THREAD

**Issue by virrapax** [senshu/Sozi-export#3]
I have been doing installation as written in readme. But executing of `npm install -g sozi-export` [in Ubuntu] gives at the end

`> slimerjs@0.9.6-2 install /usr/local/lib/node_modules/sozi-export/node_modules/slimerjs`
`> node install.js`

`sh: 1: node: not found`
`npm WARN This failure might be due to the use of legacy binary "node"`
`npm WARN For further explanations, please read`
`/usr/share/doc/nodejs/README.Debian`

`npm ERR! weird error 127`
`npm ERR! not ok code 0`

Could you please guess what is the source of the problem?

P. S. I have no "node" packages installed.

**Comment by aumouvantsillage** [comment]
You can try to install node.js via NodeSource. See the [installation instructions for your distribution](https://github.com/nodesource/distributions#debinstall).

Sozi-export is known to work with node.js 0.10 and 0.12.
Later versions have not been tested.

**Comment by virrapax** [comment]
This solved the problem. Thanks!
