### ISSUE TITLE
Save as .png files?

### ISSUE THREAD

**Issue by tweetthedebates** [senshu/Sozi-export#4]
With sozi2video, I slightly hacked the program so that I could just save .png files for each frame exported.  That makes it easier for me to use the files in Blender.  I can't figure out how to do this now with sozitovideo.

Thank you very much for these excellent programs! They are extremely helpful!

**Comment by aumouvantsillage** [comment]
sozi-to-video generates a sequence of PNG files to a temporary directory.
If you want to keep them, you can modify the function `convertToVideo` in [lib/index.js](https://github.com/senshu/Sozi-export/blob/master/lib/index.js) like this:
- In the call to `tmp.dirSync()`, set the argument to `{unsafeCleanup: false}` to prevent deleting the temporary directory.
- Add a statement `console.log(tmpDir.name)` to display the name of the temporary directory.
- If you don't want to generate a video, remove or comment the statement `resp = execSync("avconv", ...)`

**Comment by tweetthedebates** [comment]
That works great.  Thank you kindly!
