### ISSUE TITLE
How to install sozi?

### ISSUE THREAD

**Issue by Shelvak** [senshu/Sozi-export#8]
Hi there I tried to install sozi withh npm install and then in `sozi-to-video.js` add `sozi = require("Sozi")` but I always have a bad parsed "index.html".

export depends on sozi, would be really great that you write a little guide with Install steps to get it work.

Thanks in advance.

The error:

```
# After try to convert
$ cat /tmp/sync-exec-961816626/stdout

Script Error: Module: Can not resolve "Sozi" module required by main located at file:///usr/lib/node_modules/sozi-export/lib/sozi-to-video.js
       Stack:
         -> file:///usr/lib/node_modules/sozi-export/lib/sozi-to-video.js: 350


 $ node
> require("Sozi")

/usr/lib/node_modules/Sozi/index.html:2
   - License, v. 2.0. If a copy of the MPL was not distributed with this
                 ^^^

```

I tried with node 0.10 and 0.12

if I delete the licence comment I have.

```
sozi/index.html:1
(function (exports, require, module, __filename, __dirname) { "<!doctype html>
                                                              ^^^^^^^^^^^^^^^^
```

**Comment by aumouvantsillage** [comment]
I'm sorry but I don't understand what you are trying to do.

The installation instructions for Sozi-export are available at the home page of this GitHub project:
https://github.com/senshu/Sozi-export

**Comment by aumouvantsillage** [comment]
If your goal is to install Sozi, then you are reporting this issue in the wrong project.
Have you tried the instructions at http://sozi.baierouge.fr/pages/20-install.html ?

**Comment by Shelvak** [comment]
Hey sorry for the delay, and thanks for the answers.

I have an inkscape-sozi presentation. And want to convert this to a video. So I installed sozi-export like you explain in the README but when I ran  `sozi-to-video foo.html` I get:

```
Converting foo.html to foo.ogv

Script Error: Error: sozi is not defined
       Stack:
         -> phantomjs://webpage.evaluate(): 60
         -> phantomjs://webpage.evaluate(): 60
         -> phantomjs://webpage.evaluate(): 1


Script Error: Error: sozi is not defined
       Stack:
         -> phantomjs://webpage.evaluate(): 5
         -> phantomjs://webpage.evaluate(): 5 (in function main)
         -> phantomjs://webpage.evaluate(): 1
```

Because you're calling `sozi` everywhere like https://github.com/senshu/Sozi-export/blob/master/lib/sozi-to-video.js#L33 but you never define `sozi`... What can  i fix that?

**Comment by aumouvantsillage** [comment]
> you're calling sozi everywhere like [...] but you never define sozi

`sozi` should be defined inside the HTML file that you are trying to convert.
If the HTML has been output by the Sozi presentation editor, then it should contain a copy of the JavaScript of the Sozi player.

I have tried to convert a sample HTML file that has not been created with Sozi and I get the same error messages as you.

Can you check the content of your HTML file and see if the Sozi player is there?

**Comment by Shelvak** [comment]
Oh great point. I was exporting from inkscape directly.
I export with inkscape and then reopen with sozi, and now that works :D 
Maybe for future _issues_ like this, you could add a note like "use sozi presentation app instead of inkscape for export html" because a lot of people use directly inkscape :)

Thanks!

**Comment by aumouvantsillage** [comment]
> Maybe for future issues like this, you could add a note like "use sozi presentation app instead of inkscape for export html" because a lot of people use directly inkscape :)

Well, I think that a lot of people use the Sozi editor to create Sozi presentations. I don't see how you can "use directly Inkscape" and what kind of result you expect.

You can find explanations about the files generated by Sozi [in this tutorial](http://sozi.baierouge.fr/pages/tutorial-first.html):

> When saving, the editor updates the following two files:
> - first-presentation.sozi.json contains the presentation data. This file is used by the presentation editor. It must reside in the same folder as the SVG document and must have the same name.
> - first-presentation.sozi.html contains the complete presentation. You can display it in a web browser to play the presentation.

I have never imagined that one would export HTML from Inkscape
